let categorias = ['ANIMAIS', 'COMIDAS', 'ESPORTES', 'HOBBIES', 'PROFISSÕES', 'TODAS AS CATEGORIAS'];
let sorteiaAnimal = ['ARARA', 'ANDORINHA', 'HIENA', 'ORNITORRINCO', 'ORANGOTANGO', 'LONTRA', 'PANDA', 'OVELHA', 'BALEIA',
'GUAXINIM', 'FLAMINGO', 'IGUANA', 'SARDINHA', 'CANGURU', 'PANTERA'];
let sorteiaComida = ['CALZONE', 'SORVETE', 'ABACATE', 'GORGONZOLA', 'BISCOITO', 'TEMAKI', 'PASTEL', 'ESPAGUETE', 'LINGUIÇA',
'BRIGADEIRO', 'BERINJELA', 'ALCACHOFRA', 'EMPADA', 'GUISADO', 'INHAME', 'ESCONDIDINHO'];
let sorteiaEsportes = ['FUTEBOL', 'AUTOMOBILISMO', 'PARAQUEDISMO', 'BADMINTON', 'TAEKWONDO', 'BASQUETE', 'CURLING',
'CAPOEIRA', 'CICLISMO', 'ATLETISMO', 'HANDEBOL', 'LACROSSE', 'SNOWBOARD', 'ESGRIMA', 'RUGBY'];
let sorteiaHobbies = ['MEDITAR', 'ARTESANATO', 'FOTOGRAFIA', 'COSTURA', 'ESCALADA', 'COZINHAR', 'PINTURA', 'CORRIDA',
'DANÇAR', 'COLECIONAR', 'JARDINAGEM', 'VIAJAR', 'LEITURA'];
let sorteiaProfissoes = ['ADVOGADO', 'ARQUITETO', 'POLICIAL', 'BOMBEIRO', 'FAXINEIRO', 'PROFESSOR', 'ELETRICISTA',
'HISTORIADOR', 'FIGURINISTA', 'MARCENEIRO', 'JOALHEIRO', 'PADEIRO'];
let sorteiaTodas = ['ANDORINHA', 'ORNITORRINCO', 'IGUANA', 'CANGURU', 'PANTERA',
'GORGONZOLA', 'BISCOITO', 'TEMAKI', 'GUISADO', 'ESCONDIDINHO',
'AUTOMOBILISMO', 'HANDEBOL', 'LACROSSE', 'BASQUETE', 'LACROSSE',
'ARTESANATO', 'JARDINAGEM', 'FOTOGRAFIA', 'COZINHAR', 'COLECIONAR',
'HISTORIADOR', 'FIGURINISTA', 'FAXINEIRO', 'ELETRICISTA', 'JOALHEIRO'];
